version: '2.2'

services:
    node_api:
        container_name: node_api
        build:
            context: .
            dockerfile: .docker/node/Dockerfile
        command: ["yarn", "start"]
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "${APP_PORT}:80"
        restart: always

    mongodb:
        image: mongo:3-xenial
        ports:
            - "${DB_PORT}:80"
