version: '2.2'

services:
    node_api:
        container_name: node_api
        build:
            context: .
            dockerfile: .docker/node/Dockerfile
        command: ["yarn", "start"]
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "${APP_PORT}:80"
        restart: always
        depends_on:
          - mongodb

    mongodb:
        image: mongo:4.2
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
        volumes:
            - ./.data:/data/db
        ports:
            - "${DB_PORT}:27017"
